// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type ExecveEventT struct {
	TsNs          uint64
	Pid           uint32
	Ppid          uint32
	Uid           uint32
	Gid           uint32
	Retval        int32
	Comm          [16]int8
	Filename      [256]int8
	Argv          [2560]int8
	ArgvTruncated uint8
	Pad           [3]uint8
}

// LoadExecve returns the embedded CollectionSpec for Execve.
func LoadExecve() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecveBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Execve: %w", err)
	}

	return spec, err
}

// LoadExecveObjects loads Execve and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ExecveObjects
//	*ExecvePrograms
//	*ExecveMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadExecveObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadExecve()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ExecveSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecveSpecs struct {
	ExecveProgramSpecs
	ExecveMapSpecs
}

// ExecveSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecveProgramSpecs struct {
	HandleEnter *ebpf.ProgramSpec `ebpf:"handle_enter"`
	HandleExit  *ebpf.ProgramSpec `ebpf:"handle_exit"`
}

// ExecveMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecveMapSpecs struct {
	Events   *ebpf.MapSpec `ebpf:"events"`
	Inflight *ebpf.MapSpec `ebpf:"inflight"`
	Scratch  *ebpf.MapSpec `ebpf:"scratch"`
}

// ExecveObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadExecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecveObjects struct {
	ExecvePrograms
	ExecveMaps
}

func (o *ExecveObjects) Close() error {
	return _ExecveClose(
		&o.ExecvePrograms,
		&o.ExecveMaps,
	)
}

// ExecveMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadExecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecveMaps struct {
	Events   *ebpf.Map `ebpf:"events"`
	Inflight *ebpf.Map `ebpf:"inflight"`
	Scratch  *ebpf.Map `ebpf:"scratch"`
}

func (m *ExecveMaps) Close() error {
	return _ExecveClose(
		m.Events,
		m.Inflight,
		m.Scratch,
	)
}

// ExecvePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadExecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecvePrograms struct {
	HandleEnter *ebpf.Program `ebpf:"handle_enter"`
	HandleExit  *ebpf.Program `ebpf:"handle_exit"`
}

func (p *ExecvePrograms) Close() error {
	return _ExecveClose(
		p.HandleEnter,
		p.HandleExit,
	)
}

func _ExecveClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed execve_bpfel.o
var _ExecveBytes []byte
